global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'api_main_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['main:8000']

  - job_name: 'websocket_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['websocket:8001']
